runqemu-export-rootfs: refactor to allow more protocols than NFS
Despite the generic name, the script is pretty much tailored in its
parameters, variable names and functionality to NFS.

In preparation for adding 9P export support via diod, refactor it, so
the generic option parsing and command handling are separated from the
NFS specific bits.

This patches introduces functional changes for existing users:
NFS_INSTANCE has been renamed to INSTANCE, and MOUNTD_PORT and NFSD_PORT
have been combined into a single PORT. It's ok to set them to the same
port and the only in-tree user, scripts/runqemu, does this already, so
it shouldn't cause much issue to just remove the ability to set them
differently when calling the script.

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>

diff --git a/scripts/runqemu-export-rootfs b/scripts/runqemu-export-rootfs
--- a/scripts/runqemu-export-rootfs
+++ b/scripts/runqemu-export-rootfs
@@ -6,16 +6,34 @@
 #
 
 usage() {
-	echo "Usage: $0 {start|stop|restart} <nfs-export-dir>"
+	echo "Usage: [-fip] $0 {start|stop|restart} <export-dir>"
+	echo ''
+	echo 'you can specify via env or option'
+	echo 'env         option'
+	echo 'FS          -f      exported file system (default: nfs)'
+	echo 'INSTANCE    -i      instance'
+	echo 'PORT        -p      port to listen on (default: 3048 + $INSTANCE)'
 }
 
-if [ $# != 2 ]; then
-	usage
-	exit 1
-fi
+while getopts "f:p:" o; do
+	case "${o}" in
+		i)
+			INSTANCE=$OPTARG
+			;;
+		p)
+			PORT=$OPTARG
+			;;
+		f)
+			FS=$OPTARG
+			;;
+		*)
+			usage
+			;;
+	esac
+done
+shift $((OPTIND-1))
 
-if [[ "$1" != "start" && "$1" != "stop" && "$1" != "restart" ]]; then
-	echo "Unknown command '$1'"
+if [ $# != 2 ]; then
 	usage
 	exit 1
 fi
@@ -25,8 +43,9 @@ if [ ! -d "$2" ]; then
 	usage
 	exit 1
 fi
-# Ensure the nfs-export-dir is an absolute path
-NFS_EXPORT_DIR=$(cd "$2" && pwd)
+
+# Ensure the export-dir is an absolute path
+EXPORT_DIR=$(cd "$2" && pwd)
 
 SYSROOT_SETUP_SCRIPT=`which oe-find-native-sysroot 2> /dev/null`
 if [ -z "$SYSROOT_SETUP_SCRIPT" ]; then
@@ -36,92 +55,141 @@ if [ -z "$SYSROOT_SETUP_SCRIPT" ]; then
 fi
 . $SYSROOT_SETUP_SCRIPT qemu-helper-native
 
-if [ ! -e "$OECORE_NATIVE_SYSROOT/usr/bin/unfsd" ]; then
-	echo "Error: Unable to find unfsd binary in $OECORE_NATIVE_SYSROOT/usr/bin/"
+# Parameter defaults
+FS=${FS:-nfs}
+INSTANCE=${INSTANCE:-0}
+PORT=${PORT:=$[ 3048 + $INSTANCE ]}
+PIDFILE=~/.runqemu-sdk/$FS$INSTANCE.pid
+
+### namespace: nfs ###
+
+if [ -n "${NFS_INSTANCE}${NFSD_PORT}${MOUNTD_PORT}" ]; then
+	echo "Error: Variables NFS_INSTANCE/NFSD_PORT/MOUNTD_PORT " \
+	     "have been replaced by INSTANCE/PORT/PORT command line arguments."
+	usage
+	exit 1
+fi
+
+EXPORTS=~/.runqemu-sdk/exports$INSTANCE
+RMTAB=~/.runqemu-sdk/rmtab$INSTANCE
+MOUNTPID=~/.runqemu-sdk/mount$INSTANCE.pid
+
+VAR_nfs_SERVER="$OECORE_NATIVE_SYSROOT/usr/bin/unfsd"
+VAR_nfs_ROOTOPTS="nfsroot=IP_ADDRESS:$EXPORT_DIR,nfsvers=3,port=$PORT,udp,mountport=$PORT"
+
+## For debugging you would additionally add
+## --debug all
+UNFSD_OPTS="-p -i $PIDFILE -e $EXPORTS -n $PORT -m $PORT"
+
+do_nfs_prep () {
+	echo "Creating exports file..."
+	echo "$EXPORT_DIR (rw,no_root_squash,no_all_squash,insecure)" > $EXPORTS
+}
+
+do_nfs_start () {
+	echo "Starting User Mode nfsd"
+	echo "  $PSEUDO $PSEUDO_OPTS $VAR_nfs_SERVER $UNFSD_OPTS"
+	$PSEUDO $PSEUDO_OPTS $VAR_nfs_SERVER $UNFSD_OPTS
+	if [ ! $? = 0 ]; then
+		echo "Error starting nfsd"
+		exit 1
+	fi
+}
+
+do_nfs_unprep() {
+	if [ -f "$EXPORTS" ]; then
+		echo "Removing exports file"
+		rm -f $EXPORTS
+	fi
+}
+
+### generic code ###
+
+SERVERPATH="VAR_${FS}_SERVER"
+if [ -z "${!SERVERPATH}" ]; then
+	echo "Error: unsupported file system '$FS'"
+	usage
+	exit 1
+fi
+
+if [ ! -e "${!SERVERPATH}" ]; then
+	echo "Error: ${!SERVERPATH} not found"
 
 	echo "This shouldn't happen - something is missing from your toolchain installation"
 	exit 1
 fi
 
+SERVERNAME=$(basename ${!SERVERPATH})
+
 if [ ! -d ~/.runqemu-sdk ]; then
 	mkdir -p ~/.runqemu-sdk
 fi
 
-NFS_INSTANCE=${NFS_INSTANCE:=0}
-EXPORTS=~/.runqemu-sdk/exports$NFS_INSTANCE
-RMTAB=~/.runqemu-sdk/rmtab$NFS_INSTANCE
-NFSPID=~/.runqemu-sdk/nfs$NFS_INSTANCE.pid
-MOUNTPID=~/.runqemu-sdk/mount$NFS_INSTANCE.pid
-
 PSEUDO_OPTS="-P $OECORE_NATIVE_SYSROOT/usr"
-PSEUDO_LOCALSTATEDIR="$NFS_EXPORT_DIR/../$(basename $NFS_EXPORT_DIR).pseudo_state"
+PSEUDO_LOCALSTATEDIR="$EXPORT_DIR/../$(basename $EXPORT_DIR).pseudo_state"
 export PSEUDO_LOCALSTATEDIR
 
 if [ ! -d "$PSEUDO_LOCALSTATEDIR" ]; then
 	echo "Error: $PSEUDO_LOCALSTATEDIR does not exist."
 	echo "Did you create the export directory using runqemu-extract-sdk?"
-	exit 1	
+	exit 1
 fi
 
-# NFS server port number
-NFSD_PORT=${NFSD_PORT:=$[ 3049 + 2 * $NFS_INSTANCE ]}
-# mountd port number
-MOUNTD_PORT=${MOUNTD_PORT:=$[ 3048 + 2 * $NFS_INSTANCE ]}
+fs_call () {
+	command_func="do_${FS}_${1}"
+	if ! declare -F | grep " ${command_func}$" &>/dev/null; then
+		return 3 # indicates a bug during addition of new FS
+	fi
 
-## For debugging you would additionally add
-## --debug all
-UNFSD_OPTS="-p -i $NFSPID -e $EXPORTS -n $NFSD_PORT -m $MOUNTD_PORT"
+	shift
+
+	"${command_func}" "$@"
+}
 
 # See how we were called.
 case "$1" in
-  start)
-	echo "Creating exports file..."
-	echo "$NFS_EXPORT_DIR (rw,no_root_squash,no_all_squash,insecure)" > $EXPORTS
+	start)
+		fs_call prep
+		fs_call start || exit 3
 
-	echo "Starting User Mode nfsd"
-	echo "  $PSEUDO $PSEUDO_OPTS $OECORE_NATIVE_SYSROOT/usr/bin/unfsd $UNFSD_OPTS"
-	$PSEUDO $PSEUDO_OPTS $OECORE_NATIVE_SYSROOT/usr/bin/unfsd $UNFSD_OPTS
-	if [ ! $? = 0 ]; then
-		echo "Error starting nfsd"
-		exit 1
-	fi
-	# Check to make sure everything started ok.
-	if [ ! -f $NFSPID ]; then
-		echo "rpc.nfsd did not start correctly"
-		exit 1
-	fi
-	ps -fp `cat $NFSPID` > /dev/null 2> /dev/null
-	if [ ! $? = 0 ]; then
-		echo "rpc.nfsd did not start correctly"
-		exit 1
-	fi
-	echo " "
-	echo "On your target please remember to add the following options for NFS"
-	echo "nfsroot=IP_ADDRESS:$NFS_EXPORT_DIR,nfsvers=3,port=$NFSD_PORT,udp,mountport=$MOUNTD_PORT"
+		# Check to make sure everything started ok.
+		if [ ! -f $PIDFILE ]; then
+			echo "$SERVERNAME did not start correctly"
+			exit 1
+		fi
+		ps -fp `cat $PIDFILE` > /dev/null 2> /dev/null
+		if [ ! $? = 0 ]; then
+			echo "$SERVERNAME did not start correctly"
+			exit 1
+		fi
+		echo " "
+		echo "On your target please remember to add the following options:"
+		ROOTOPTS="VAR_${FS}_ROOTOPTS"
+		echo "${!ROOTOPTS}"
+		;;
+
+	stop)
+		if [ -f "$PIDFILE" ]; then
+			echo "Stopping $SERVERNAME"
+			kill `cat $PIDFILE`
+			rm -f $PIDFILE
+		else
+			echo "No PID file, not stopping $SERVERNAME"
+		fi
+
+		fs_call unprep
 	;;
-  stop)
-	if [ -f "$NFSPID" ]; then
-		echo "Stopping rpc.nfsd"
-		kill `cat $NFSPID`
-		rm -f $NFSPID
-	else
-		echo "No PID file, not stopping rpc.nfsd"
-	fi
-	if [ -f "$EXPORTS" ]; then
-		echo "Removing exports file"
-		rm -f $EXPORTS
-	fi
-	;;
-  restart)
-	$0 stop $NFS_EXPORT_DIR
-	$0 start $NFS_EXPORT_DIR 
-	if [ ! $? = 0 ]; then
+
+	restart)
+		$0 stop $EXPORT_DIR
+		$0 start $EXPORT_DIR
+		if [ ! $? = 0 ]; then
 		exit 1
-	fi
-	;;
-  *)
-	echo "$0 {start|stop|restart} <nfs-export-dir>"
-	;;
+		fi
+		;;
+	*)
+		usage
+		;;
 esac
 
 exit 0
